# Generated by Django 3.2.13 on 2022-04-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdpr_helpers', '0009_auto_20211116_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalreasongroup',
            name='connected_to',
            field=models.JSONField(default=dict, max_length=100, verbose_name='Form collegato'),
        ),
    ]
